### ISSUE TITLE
Controlling the version numbers to follow semantic versioning patterns

### ISSUE THREAD

**Issue by thelinuxer** [mrhwick/django-rest-framework-version-transforms#10]
Hi, 

I want to implement API versioning following the rules from [semver](http://semver.org/). According to the documentation we define the transform functions and use them in serializers/parsers. There is no mention of where we define the versioning schemes.

This makes me assume that v1, v2 ..etc scheme is the one used by default. Am I am wrong ?

If I am wrong, can you please help me understand how to define a different versioning scheme from the default? 

Thanks.

**Comment by mrhwick** [comment]
This is an interesting idea, but I'm not sure I see any obvious advantages to using semver for API versioning. Here's my reasoning:

## Incompatible / Major Versions
In semantic versioning, an incompatible change is represented by the major version number increment. This directly translates to RESTful API versioning as a new major version of your API. An example of an incompatible change would be something like this:

v1 representation of some super simple object:
```
{"name": "Matt Hardwick"}
```
v2 representation of the same object:
```
{"first_name": "Matt", "last_name": "Hardwick"}
```
This would require a transform that splits the former name field on the way into your endpoint, and merges the `first_name` and `last_name` fields on the way back out to the client.

You can often make seemingly incompatible changes in ways that will maintain backwards compatibility. For example, you could simple add the `first_name` and `last_name` fields without removing the `name` field to create a compatible version of these changes that does not demand a new API version:

```
{"name": "Matt Hardwick", "first_name": "Matt", "last_name": "Hardwick"}
```
Now clients can use either the same combined `name` field which they were using before, but can also use the `first_name` and `last_name` fields if they want those instead.

## Compatible / Minor Versions

In semantic versioning, a compatible change is represented by the minor version number increment. In RESTful API versioning, a compatible change does not demand a new version of your API. You can add compatible changes to existing versions without creating problems for your clients. An example of a compatible change would be something like this:

v1 representation of a simple object:
```
{"name": "Matt Hardwick"}
```
New v1 representation of the same object:
```
{"name": "Matt Hardwick", "location": "Chattanooga"}
```
This doesn't require a transform, since the client can still interact with all of the fields that it expects to be a part of the object. Any client that is compatible with v1 of this API would function without changes against an altered v1 of the same API that only introduces backwards-compatible changes. In the example, this would mean clients can still interact with the `name` field as before, and ignore the `location` field until they wish to use it for some reason.

## Compatible / Patch Versions

This works the same for patch versions. In semantic versioning, a patch change is represented by the patch number increment. In RESTful API versioning, a patch can simply be made without incrementing the API version without creating any problems for your clients. Patches are just like any other compatible change, in that clients need not make any changes to their code to maintain correct execution. An example of a compatible patch change would be something like this:

v1 representation with a bug on populating the location field:
```
{"name": "Matt Hardwick", "location": ""}
```
Patched v1 representation with that bug fixed:
```
{"name": "Matt Hardwick", "location": "Chattanooga"}
```
Patches are really just fixing the current implementation of your API to do the documented behavior, as in this example we fix the bug and begin returning the location as expected.

**Comment by thelinuxer** [comment]
I am sorry I am just replying now. Your answer is very logical. Thanks.
